import requests
r = requests.get('http://127.0.0.1:5000/users')
print(r.status_code, r.headers, r.text, r.json())
r = requests.post('http://127.0.0.1:5000/users', json={"id": 2, "name": "Peter", "surname": "Jan"})
print(r.json())
r = requests.post('http://127.0.0.1:5000/users', json={"id": 4, "name": "Peter", "surname": "Jan"})
print(r.json())
r = requests.delete('http://127.0.0.1:5000/users', json={"id": 2})
print(r.json())
r = requests.put('http://127.0.0.1:5000/users', json={"id": 1, "name": "New", "surname": "York"})
print(r.json())
